CrudNet8MVC/Models/Contacto.cs
using System.ComponentModel.DataAnnotations;

namespace CrudNet8MVC.Models
{
    public class Contacto
    {
        //Crear cada atributo de la tabal contacto
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El Nombre es obligatorio")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El Telefono es obligatorio")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "El Celular es obligatorio")]
        public string Celular { get; set; }

        [Required(ErrorMessage = "El Email es obligatorio")]
        public string Email { get; set; }
        //fecha de creacion
        public DateTime FechaCreacion { get; set; }
    }
}

CrudNet8MVC/Models/ErrorViewModel.cs
namespace CrudNet8MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNet8MVC/Controllers/InicioController.cs
using CrudNet8MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using CrudNet8MVC.Datos;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8MVC.Controllers
{
    public class InicioController : Controller
    {
        //private readonly ILogger<InicioController> _logger;

        //crear variable para la base de datos
        private readonly ApplicationDbContext _contexto;

        public InicioController(ApplicationDbContext contexto)
        {
            //_logger = logger;
            _contexto = contexto;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _contexto.Contacto.ToListAsync());
        }

        /*INICIO*/
        //crear metodo CREAR y su vista correspondiente
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        //metodo POST para guardar los datos
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(Contacto contacto)
        {
            //validar si los datos son correctos
            if (ModelState.IsValid)
            {
                //Agregar la fecha y hora de creacion]
                contacto.FechaCreacion = DateTime.Now;

                _contexto.Add(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        /*FIN*/


        /*INICIO-EDITAR*/
        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();  
            }
            var contact =  _contexto.Contacto.Find(id);

            if (contact == null)
            {
                return NotFound();
            }

           return  View(contact);
        }

        //metodo para editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            //validar si los datos son correctos
            if (ModelState.IsValid)
            {
                _contexto.Update(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        /*FIN*/

        /*INICIO-DETALLE*/
        [HttpGet]
        public IActionResult Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var contact = _contexto.Contacto.Find(id);

            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }
        //FIN

        //Metodo borrar
        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var contact = _contexto.Contacto.Find(id);

            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarContacto(int? id)
        {
            var contact = await _contexto.Contacto.FindAsync(id);
            if (contact == null)
            {
                return View();
            }
            //Borrar contacto
            _contexto.Contacto.Remove(contact);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        //Fin

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNet8MVC/Views/Inicio/Borrar.cshtml
@model CrudNet8MVC.Models.Contacto

@{
    ViewData["Title"] = "Borrar contactos";
}

<h1 class="text-center">Lista de Contactos - Net core 8</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        BORRAR CONTACTO
                    </strong>
                </h3>
            </div>
            <div class="card-body">
                @* creando formulario por el metodo post *@
                <form asp-action="Borrar">
                    @* mandamos el ID del contacto *@
                    <input asp-for="Id" type="hidden" />


                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" readonly/>
                        <span asp-validation-for="Nombre" class="text-danger"></span>

                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" readonly/>
                        <span asp-validation-for="Telefono" class="text-danger"></span>

                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" readonly/>
                        <span asp-validation-for="Celular" class="text-danger"></span>


                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" readonly/>
                        <span asp-validation-for="Email" class="text-danger"></span>


                        <div class="form-group mt-3">
                            <button type="submit" class="btn btn-success d-block mx-auto">
                                <i class="fa-solid fa-user-plus"></i>
                                Borrar Usuario
                            </button>
                        </div>
                    </div>
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-secondary">Regresar</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Crear.cshtml
@model CrudNet8MVC.Models.Contacto

@{
    ViewData["Title"] = "Crear Nuevo contactos";
}

<h1 class="text-center">Lista de Contactos - Net core 8</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        CREAR NUEVO USUARIO
                    </strong>
                </h3>
            </div>
            <div class="card-body">
                @* creando formulario por el metodo post *@
                <form asp-action="Crear" method="POST">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingrese su nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>

                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingrese su Telefono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>

                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingrese su Celular" />
                        <span asp-validation-for="Celular" class="text-danger"></span>


                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingrese su Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>


                        <div class="form-group mt-3">
                            <button type="submit" class="btn btn-secondary d-block mx-auto">
                                <i class="fa-solid fa-user-plus"></i>
                                Agregar Usuario
                            </button>
                        </div>
                    </div>
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-secondary">Regresar</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Detalle.cshtml
@model CrudNet8MVC.Models.Contacto

@{
    ViewData["Title"] = "Detalle contactos";
}

<h1 class="text-center">Lista de Contactos - Net core 8</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        DETALLE CONTACTO
                    </strong>
                </h3>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>Nombre:</strong> @Model.Nombre
                    </li>
                    <li class="list-group-item">
                        <strong>Telefono:</strong> @Model.Telefono
                    </li>
                    <li class="list-group-item">
                        <strong>Celular:</strong> @Model.Celular
                    </li>
                    <li class="list-group-item">
                        <strong>Email:</strong> @Model.Email
                    </li>
                    <li class="list-group-item">
                        <strong>Fecha de creación:</strong> @Model.FechaCreacion
                    </li>

                </ul>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-secondary pt-4">Regresar</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Editar.cshtml
@model CrudNet8MVC.Models.Contacto

@{
    ViewData["Title"] = "Editar contactos";
}

<h1 class="text-center">Lista de Contactos - Net core 8</h1>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        EDITAR CONTACTO
                    </strong>
                </h3>
            </div>
            <div class="card-body">
                @* creando formulario por el metodo post *@
                <form asp-action="Editar">
                    @* mandamos el ID del contacto *@
                    <input asp-for="Id" type="hidden"/>
                    

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder="Ingrese su nombre"/>
                        <span asp-validation-for="Nombre" class="text-danger"></span>

                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder="Ingrese su Telefono"/>
                        <span asp-validation-for="Telefono" class="text-danger"></span>

                        <label asp-for="Celular" class="control-label"></label>
                        <input asp-for="Celular" class="form-control" placeholder="Ingrese su Celular"/>
                        <span asp-validation-for="Celular" class="text-danger"></span>


                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder="Ingrese su Email"/>
                        <span asp-validation-for="Email" class="text-danger"></span>


                        <div class="form-group mt-3">
                            <button type="submit" class="btn btn-primary d-block mx-auto">
                                <i class="fa-solid fa-user-plus"></i>
                                Editar Usuario
                            </button>
                        </div>
                    </div>
                </form>
                <a asp-controller="Inicio" asp-action="Index" class="btn btn-secondary">Regresar</a>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Inicio/Index.cshtml
@* acceder a la lista con los items de mi modelo *@
@model IEnumerable<CrudNet8MVC.Models.Contacto>

@{
    ViewData["Title"] = "Lista de contactos";
}

<h1 class="text-center">Lista de Contactos - Net core 8</h1>
<div class="row">
    <div class="offset-9 col-3 mb-3">
        <a asp-action="Crear" asp-controller="Inicio" class="btn btn-secondary d-block mx-auto btn-lg">
            <i class="fa-solid fa-plus"></i>
            Nuevo usuario
        </a>
    </div>
</div>

@* tabla de bootstrap *@
<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white">
                    <strong>
                        Lista de Usuarios
                    </strong>
                </h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @* validar los registros *@
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-bordered" id="tblUsuarios" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.Id)</th>
                                    <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                                    <th>@Html.DisplayNameFor(m => m.Celular)</th>
                                    <th>@Html.DisplayNameFor(m => m.Email)</th>
                                    <th>@Html.DisplayNameFor(m => m.FechaCreacion)</th>
                                    <th>
                                        Acciones
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Nombre</td>
                                        <td>@item.Telefono</td>
                                        <td>@item.Celular</td>
                                        <td>@item.Email</td>
                                        <td>@item.FechaCreacion</td>
                                        <td>
                                            <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-primary">
                                                <i class="fa-solid fa-pen-to-square"></i>
                                                Editar
                                            </a>
                                            <a asp-action="Detalle" asp-route-id="@item.Id" class="btn btn-warning">
                                                <i class="fa-solid fa-circle-info"></i>
                                                Detalles
                                            </a>
                                            <a asp-action="Borrar" asp-route-id="@item.Id" class="btn btn-danger">
                                                <i class="fa-solid fa-eraser"></i>
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-warning">
                            <strong>No hay registros</strong>
                        </div>
                    }
                    
                </div>
            </div>
        </div>
    </div>
</div>

CrudNet8MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNet8MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudNet8MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">CrudNet8MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudNet8MVC - <a asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>